import type { CSSProperties } from 'react';
import {
  ArrowDownToLine,
  ArrowLeft,
  ArrowUpFromLine,
  ArrowUpRight,
  AudioLines,
  Ban,
  BarChart3,
  BookOpen,
  Bookmark,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Car,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronUp,
  CircleCheck,
  CircleHelp,
  CircleX,
  ClipboardList,
  Clock3,
  Compass,
  Ear,
  EyeOff,
  Flame,
  FlaskConical,
  Globe2,
  GraduationCap,
  Handshake,
  Heart,
  Headphones,
  Hotel,
  House,
  Landmark,
  Languages,
  Laptop,
  Lightbulb,
  LoaderCircle,
  LogOut,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  MonitorCog,
  Music2,
  PartyPopper,
  Pill,
  Plane,
  Play,
  Presentation,
  Puzzle,
  Repeat2,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Stethoscope,
  Store,
  Target,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Type,
  Undo2,
  UserRound,
  Utensils,
  Volume2,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICONS = {
  arrowDown: ArrowDownToLine,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUpFromLine,
  arrowUpRight: ArrowUpRight,
  audio: AudioLines,
  ban: Ban,
  bank: Landmark,
  barChart: BarChart3,
  book: BookOpen,
  bookmark: Bookmark,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarDays,
  car: Car,
  chart: ChartColumn,
  check: Check,
  checkCircle: CircleCheck,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  clipboard: ClipboardList,
  clock: Clock3,
  compass: Compass,
  ear: Ear,
  eyeOff: EyeOff,
  flame: Flame,
  flask: FlaskConical,
  globe: Globe2,
  graduation: GraduationCap,
  handshake: Handshake,
  heart: Heart,
  headphones: Headphones,
  help: CircleHelp,
  home: House,
  hotel: Hotel,
  languages: Languages,
  laptop: Laptop,
  lightbulb: Lightbulb,
  loader: LoaderCircle,
  logout: LogOut,
  mapPin: MapPin,
  megaphone: Megaphone,
  message: MessageCircle,
  mic: Mic,
  monitorCog: MonitorCog,
  music: Music2,
  party: PartyPopper,
  pharmacy: Pill,
  plane: Plane,
  play: Play,
  presentation: Presentation,
  puzzle: Puzzle,
  repeat: Repeat2,
  rocket: Rocket,
  rotate: RotateCcw,
  save: Save,
  search: Search,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shopping: ShoppingBag,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  stethoscope: Stethoscope,
  stop: Square,
  store: Store,
  target: Target,
  trash: Trash2,
  trending: TrendingUp,
  triangleAlert: TriangleAlert,
  trophy: Trophy,
  type: Type,
  undo: Undo2,
  user: UserRound,
  utensils: Utensils,
  volume: Volume2,
  wrench: Wrench,
  x: X,
  xCircle: CircleX,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface IconProps {
  name: IconName;
  size?: number;
  strokeWidth?: number;
  className?: string;
  style?: CSSProperties;
  label?: string;
}

export function Icon({ name, size = 18, strokeWidth = 2, className, style, label }: IconProps) {
  const Component = ICONS[name];
  return (
    <Component
      className={className ? `app-icon ${className}` : 'app-icon'}
      width={size}
      height={size}
      strokeWidth={strokeWidth}
      style={style}
      aria-hidden={label ? undefined : true}
      aria-label={label}
    />
  );
}
