import { useEffect, useState } from 'react';
import { ArrowRight, AudioLines, BookOpen, Bot, CheckCheck, CircleHelp, Clock3, CreditCard, ListChecks, Loader2, RefreshCw, ShieldCheck, Sparkles, TriangleAlert, TrendingUp } from 'lucide-react';
import { COMPETENCY_LABELS_RO } from '../types';
import TelemetryPanel from './TelemetryPanel';
import { number, summarize } from './metrics';
import { adminRequest } from './api';
import type { AdminError, AdminUser, AuditEntry, BackendStatus, OpenRouterInfo } from './types';
import { SERVICE_LABELS } from './Configuration';
import { ActivityChart, Bars, Empty, Panel, Stat } from './ui';

export function LearningPanel({ users, metrics, ready, onUsers }: { users: AdminUser[]; metrics: ReturnType<typeof summarize>; ready: boolean; onUsers: () => void }) {
  return <><div className="admin-stats-grid"><Stat icon={Clock3} label="Timp activ în aplicație" value={ready ? `${number(Math.round(metrics.appActiveSec / 60))} min` : '—'} note="numai timp activ măsurat" /><Stat icon={BookOpen} label="Recapitulări vocabular" value={ready ? number(metrics.reviews) : '—'} note="în perioada selectată" tone="blue" /><Stat icon={AudioLines} label="Pronunție & shadowing" value={ready ? number(metrics.pronunciation) : '—'} note="fraze exersate" tone="green" /><Stat icon={Sparkles} label="XP câștigat" value={ready ? number(metrics.xp) : '—'} note="în perioada selectată" tone="orange" /></div><Panel title="Evoluția activității" caption="Date zilnice din aplicația web și mobilă">{ready ? <ActivityChart points={metrics.series} /> : <Empty />}</Panel><div className="admin-equal-grid"><Panel title="Competențe, în medie" caption="Scoruri curente de profil (0–100), indiferent de perioada selectată">{ready && users.some(u => u.profile.scores) ? <Bars items={Object.entries(COMPETENCY_LABELS_RO).map(([key, label]) => { const scores = users.map(u => u.profile.scores?.[key as keyof typeof COMPETENCY_LABELS_RO]).filter((v): v is number => typeof v === 'number' && Number.isFinite(v)); return { label: `${label} · ${scores.length} evaluări`, value: scores.length ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : 0, suffix: ' / 100' }; })} /> : <Empty title="Nu sunt disponibile evaluări" />}</Panel><Panel title="Biblioteca utilizatorilor" caption="Totaluri istorice pentru conturile încărcate"><div className="admin-collection-grid">{[['Sesiuni', users.reduce((n, u) => n + (u.totals?.sessions || 0), 0)], ['Cuvinte & expresii', users.reduce((n, u) => n + (u.totals?.vocab || 0), 0)], ['Greșeli urmărite', users.reduce((n, u) => n + (u.totals?.mistakes || 0), 0)], ['Lecții bifate în perioadă', metrics.lessons]].map(([label, value]) => <div key={label}><strong>{ready ? number(Number(value)) : '—'}</strong><span>{label}</span></div>)}</div><p className="admin-caption">Deschide un utilizator pentru lecții, teste, rapoarte, expresii și greșeli individuale.</p><button className="admin-text-button" onClick={onUsers}>Explorează parcursurile<ArrowRight size={15} /></button></Panel></div></>;
}

export function AiPanel({ days, credits, status, errors, onRetry, onSettings, preview = false, refreshVersion = 0 }: { preview?: boolean; refreshVersion?: number; days: number; credits: OpenRouterInfo | null; status: BackendStatus | null; errors: string[]; onRetry: () => void; onSettings: () => void }) {
  const money = (value?: number | null) => value == null ? '—' : new Intl.NumberFormat('ro-RO', { style: 'currency', currency: 'USD' }).format(value);
  const remaining = credits?.credits?.total_credits != null && credits.credits.total_usage != null ? credits.credits.total_credits - credits.credits.total_usage : null;
  return <>{errors.map(msg => <div className="admin-notice warning" key={msg}>{msg}<button onClick={onRetry}>Reîncearcă</button></div>)}<div className="admin-stats-grid"><Stat label="Credite disponibile" value={money(remaining)} icon={CreditCard} note="sold curent al contului OpenRouter" /><Stat label="Consum total cont" value={money(credits?.credits?.total_usage)} icon={TrendingUp} note="istoric, toate cheile contului" tone="blue" /><Stat label="Consum pe cheia aplicației" value={money(credits?.key?.usage)} icon={Bot} note="istoric, raportat de OpenRouter" tone="green" /><Stat label="Limita cheii" value={credits?.key ? credits.key.limit == null ? 'Nelimitată' : money(credits.key.limit) : '—'} icon={ShieldCheck} note="limita configurată în OpenRouter" tone="orange" /></div><TelemetryPanel days={days} preview={preview} refreshVersion={refreshVersion} /><Panel title="Configurația integrărilor" caption="Configurat înseamnă că există credențiale; nu este un test de disponibilitate"><div className="admin-service-cards">{Object.entries(SERVICE_LABELS).map(([key, label]) => <div key={key}><span className={`admin-dot ${status?.services[key] ? 'green' : 'amber'}`} /><span>{label}</span><small>{status ? status.services[key] ? 'Configurat' : 'Neconfigurat' : 'Necunoscut'}</small></div>)}</div><button className="admin-text-button" onClick={onSettings}>Configurare și teste<ArrowRight size={15} /></button></Panel></>;
}

export function ErrorsPanel({ errors, ready, preview, onUser, onResolved }: { errors: AdminError[]; ready: boolean; preview: boolean; onUser: (uid: string) => void; onResolved: (uid: string, id: string, resolved: boolean) => void }) {
  const [filter, setFilter] = useState('open');
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const filtered = errors.filter(e => filter === 'all' || (filter === 'resolved' ? e.resolved : !e.resolved));
  async function resolve(event: AdminError) {
    if (preview || busy) return;
    setBusy(`${event.uid}:${event.id}`); setError('');
    try { await adminRequest('error-status', { uid: event.uid, errorId: event.id, resolved: !event.resolved }); onResolved(event.uid, event.id, !event.resolved); }
    catch (e) { setError(e instanceof Error ? e.message : String(e)); }
    finally { setBusy(''); }
  }
  return <><div className="admin-small-stats">{[['Evenimente încărcate', errors.length], ['Deschise', errors.filter(e => !e.resolved).length], ['Rezolvate', errors.filter(e => e.resolved).length], ['Utilizatori afectați', new Set(errors.map(e => e.uid)).size]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{ready ? value : '—'}</strong></div>)}</div><Panel title="Erori raportate" caption="Maximum 20 de evenimente recente per cont, în perioada aleasă" action={<div className="admin-segments">{[['open', 'Deschise'], ['resolved', 'Rezolvate'], ['all', 'Toate']].map(([id, label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div>}>{error && <div className="admin-notice error" role="alert">{error}</div>}{filtered.length ? filtered.map(e => <article className="admin-error-row" key={`${e.uid}:${e.id}`}><span className={`admin-error-icon ${e.resolved ? 'resolved' : ''}`}>{e.resolved ? <CheckCheck size={19} /> : <TriangleAlert size={19} />}</span><div><div className="admin-inline-badges"><span className={`admin-badge ${e.resolved ? 'green' : 'amber'}`}>{e.resolved ? 'Rezolvată' : 'Deschisă'}</span><small>{new Date(e.at).toLocaleString('ro-RO')}</small></div><h3>{e.message}</h3><p>{e.page || 'Pagină necunoscută'} · {e.source || 'Sursă necunoscută'} · v{e.version || '—'}</p><button className="admin-text-button" onClick={() => onUser(e.uid)}>{e.email}<ArrowRight size={13} /></button></div><button disabled={preview || Boolean(busy)} onClick={() => void resolve(e)}>{busy === `${e.uid}:${e.id}` ? 'Se salvează…' : e.resolved ? 'Redeschide' : 'Marchează rezolvată'}</button></article>) : <Empty title={ready ? filter === 'open' ? 'Nicio eroare deschisă în datele încărcate' : 'Nicio eroare pentru acest filtru' : 'Erorile nu sunt încă disponibile'}>Evenimentele sunt colectate de aplicație și apar aici după sincronizare.</Empty>}</Panel></>;
}

const AUDIT_LABELS: Record<string, string> = { 'update-profile': 'Profil actualizat', 'suspend-account': 'Cont suspendat', 'activate-account': 'Cont reactivat', 'save-config': 'Configurație actualizată', 'grant-pro': 'Acces Pro acordat', 'revoke-pro': 'Acces Pro revocat', 'resolve-error': 'Eroare rezolvată', 'reopen-error': 'Eroare redeschisă' };
export function AuditPanel({ users, preview, refreshVersion }: { users: AdminUser[]; preview: boolean; refreshVersion: number }) {
  const [entries, setEntries] = useState<AuditEntry[] | null>(null);
  const [busy, setBusy] = useState(true);
  const [error, setError] = useState('');
  const [version, setVersion] = useState(0);
  useEffect(() => {
    let alive = true;
    setBusy(true); setError('');
    const request = preview ? Promise.resolve({ entries: [{ id: 'demo-audit', at: new Date().toISOString(), actor: 'admin@example.com', action: 'update-profile', target: 'demo-user-1', changes: { before: { currentLevel: 'A2' }, after: { currentLevel: 'B1' } }, status: 'completed' }] }) : adminRequest<{ entries: AuditEntry[] }>('audit-log');
    request.then(result => { if (alive) setEntries(result.entries); }).catch(e => { if (alive) setError(e.message); }).finally(() => { if (alive) setBusy(false); });
    return () => { alive = false; };
  }, [preview, version, refreshVersion]);
  return <Panel title="Jurnalul modificărilor" caption="Ultimele 100 de operațiuni, începând cu activarea acestui panou" action={<button disabled={busy} onClick={() => setVersion(n => n + 1)}><RefreshCw size={15} />Actualizează</button>}>{error && <div className="admin-notice error" role="alert">{error}</div>}{busy && <div className="admin-loading"><Loader2 size={17} className="admin-spin" />Se încarcă jurnalul…</div>}{entries?.length ? entries.map(entry => <div className="admin-audit-row" key={entry.id}><span className="admin-history-icon"><ListChecks size={19} /></span><div><strong>{AUDIT_LABELS[entry.action] || entry.action}</strong><p>{entry.target} · {new Date(entry.at).toLocaleString('ro-RO')}</p><small>Administrator: {users.find(u => u.uid === entry.actor)?.auth?.email || entry.actor}</small><details><summary>Vezi modificările</summary><pre>{JSON.stringify(entry.changes, null, 2)}</pre></details></div><span className={`admin-badge ${entry.status === 'completed' ? 'green' : 'amber'}`}>{entry.status === 'completed' ? 'Finalizat' : entry.status === 'failed' ? 'Eșuat' : 'De verificat'}</span></div>) : !busy && <Empty title={error ? 'Jurnalul nu este disponibil' : 'Nicio modificare înregistrată'}>Operațiunile efectuate din acest panou vor apărea aici.</Empty>}</Panel>;
}
